stages:
  - check
  - build
  - deploy

image: python:3.6-buster

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/

pre-commit:
  stage: check
  tags:
    - build
  script:
    - pip install pre-commit
    - pre-commit run -a

# TODO enable this after got a runner which connected to all type of chips
# also need all requirements of idf, maybe use esp32-ci-env but this package only supports >=3.6 python
#check:pytest:
#  stage: check
#  tags:
#    - build
#  script:
#    - pytest

build-dist:
  stage: build
  tags:
    - build
  artifacts:
    paths:
      - dist/*
  script:
    - pip install -U pip
    - pip install wheel
    - python setup.py sdist bdist_wheel

publish:
  stage: deploy
  tags:
    - build
  dependencies:
    - build-dist
  only:
    - tags
  script:
    - pip install -U pip
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${GITLAB_HTTPS_SERVER}/api/v4/projects/${CI_PROJECT_ID}/packages/pypi --verbose dist/*
